hydra:
  run:
    dir: ./outputs/${env_name}/${hydra.job.name}/${now:%Y-%m-%d_%H%M%S_%f}

# QD
algo_name: "MAP-Elites"
seed: 42
num_iterations: 100

# Environment
env_name: "ant_omni"
episode_length: 250
env_batch_size: 256

# Archive
num_init_cvt_samples: 50000
num_centroids: 1024
min_bd: -30.
max_bd: 30.
policy_hidden_layer_sizes: [128, 128]

# GA emitter
iso_sigma: 0.005
line_sigma: 0.05
